name: hypernetbci
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python>=3.8,<3.12
  
  # Core ML/DL frameworks
  - pytorch>=1.12.0
  - pytorch-cuda=11.8  # Adjust based on your CUDA version, or use cpuonly for CPU-only
  - torchvision
  - torchaudio
  
  # Scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scikit-learn>=1.0.0
  
  # EEG/BCI specific packages
  - mne>=1.0.0
  - pip
  
  # Development and utilities
  - jupyter
  - ipython
  - tqdm
  - pathlib
  - logging
  
  # Install via pip (packages not available in conda)
  - pip:
    # BCI/EEG frameworks
    - braindecode>=0.8.0
    - moabb>=0.4.6
    
    # PyTorch ecosystem
    - pytorch-warmup>=0.1.1
    - skorch>=0.12.0
    
    # Visualization and analysis
    - seaborn>=0.11.0
    
    # Optional: for advanced visualization
    - plotly>=5.0.0
    
    # Optional: for hyperparameter tuning
    - optuna>=3.0.0
    
    # Optional: for experiment tracking
    - wandb>=0.13.0
    - tensorboard>=2.8.0
    
    # Development tools (optional)
    - black>=22.0.0
    - flake8>=4.0.0
    - pytest>=7.0.0
    - pre-commit>=2.17.0
    
    # Documentation (optional)
    - sphinx>=4.5.0
    - sphinx-rtd-theme>=1.0.0